- name: Configure my workstation quickly
  hosts: localhost
  connection: local
  become: true
  roles:
  - common
  - docker
  - terraform
  - kubernetes
  - helm
  - aws_cli
  - python-packages
  - vscode
  - insomnia
  - beekeeper
  - keepassxc
