# Acquire basic informations, configure Grub, disable unnecessary services and install common packages

- name: Install common packages from APT source
  ansible.builtin.apt:
    update_cache: yes
    name:
    - terminator
    - bash-completion
    - jq
    - xclip
    - xz-utils
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - software-properties-common
    notify:
    - Clean local repo

- name: Install Drawio from .deb package
  ansible.builtin.apt:
    deb: https://github.com/jgraph/drawio-desktop/releases/download/v20.6.2/drawio-amd64-20.6.2.deb
    clean: yes

- name: Add autocompletion to Bash
  ansible.builtin.blockinfile:
    path: "{{ current_home.msg }}/.bashrc"
    marker: "# Enable autocompletion"
    block: |
      source /usr/share/bash-completion/bash_completion
  become: false
  notify:
  - Source bashrc
