# Install kubectl, kubectx & kubens
# https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
# https://github.com/ahmetb/kubectx

- name: Download kubectl binary
  ansible.builtin.shell:
    cmd: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name: Download checksum file
  ansible.builtin.shell:
    cmd: curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"

- name: Validate checksum
  ansible.builtin.shell:
    cmd: echo "$(cat kubectl.sha256) kubectl" | sha256sum --check

- name: Install kubectl
  ansible.builtin.shell:
    cmd: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Add autocompletion for Kubectl
  ansible.builtin.blockinfile:
    path: "{{ current_home.msg }}/.bashrc"
    marker: "# Kubectl Autocompletion"
    block: |
      source <(kubectl completion bash)
  become: false
