# Install HashiCorp Terraform
# https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli

- name: Install HashiCorp GPG key
  ansible.builtin.shell:
    cmd: >
      wget -O- https://apt.releases.hashicorp.com/gpg |
      gpg --dearmor |
      tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repo to system
  ansible.builtin.shell:
    cmd: >
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
      https://apt.releases.hashicorp.com $(lsb_release -cs) main" |
      tee /etc/apt/sources.list.d/hashicorp.list

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    update_cache: yes
    notify:
    - Clean local repo

- name: Add autocompletion for Terraform
  ansible.builtin.blockinfile:
    path: "{{ current_home.msg }}/.bashrc"
    marker: "# Terraform Autocompletion"
    block: |
      complete -C /usr/bin/terraform terraform
  become: false
  notify:
  - Source bashrc