# Configure Grub, disable unnecessary services and install common packages

- name: Configure Grub to ignore errors on certain drivers
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=).*$'
    replace: '\1"quiet splash pci=noaer pcie_aspm=off"'
    backup: yes

- name: Update GRUB after modification
  ansible.builtin.command:
    cmd: update-grub

- name: Stop and disable Apache2
  ansible.builtin.service:
    name: apache2
    state: stopped
    enabled: no

- name: Install common packages
  ansible.builtin.apt:
    update_cache: yes
    name:
    - terminator
    - bash-completion
    - xclip
    - xz-utils
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - software-properties-common

- name: Add autocompletion to Bash
  ansible.builtin.blockinfile:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    marker: "# Enable autocompletion"
    block: |
      source /usr/share/bash-completion/bash_completion
  become: false
