# Acquire basic information

- name: Acquire current user
  become: false
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'USER') }}"
  register: current_user

- name: Acquire current home directory
  become: false
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'HOME') }}"
  register: current_home

- name: Create 'repos' folder in home directory
  become: false
  ansible.builtin.file:
    path: "{{ current_home.msg }}/repos"
    state: directory
  register: repos_folder
